# Homebrew formula template for ccync — cross-agent plugin / MCP / skills manager
# Placeholders (fill in from checksums.txt after publishing the GitHub Release):
#   v0.1.4             — exact GitHub Release tag (e.g. v0.1.0); used in URLs
#   0.1.4     — version without leading v (e.g. 0.1.0); used in `version`
#   9fe6fa1bc746780bff30b2ddbe2b0ff12e643496813a413b985b14b94842d06f   — SHA-256 of ccync-v0.1.4-darwin-x64.tar.gz
#   ab983e3f46bc19ab15bad6cef764dbd3d5cb6e3ed36b7eeff85fc2e24f53f3df — SHA-256 of ccync-v0.1.4-darwin-arm64.tar.gz
#   b5002f01e392a5b4587a36647924d8fcbe69d0ae8b089b20f6401ad3841c0734    — SHA-256 of ccync-v0.1.4-linux-x64.tar.gz
#   bd93190af689105eb009e88f140619225ce4c233ff4ffff4fe7271ad8b53a953  — SHA-256 of ccync-v0.1.4-linux-arm64.tar.gz
#
# Generated by: packaging/gen-release-artifacts.sh
# Submit to: https://github.com/monkey1wizard/homebrew-tap (Formula/ccync.rb)
class Ccync < Formula
  desc "Cross-agent plugin / MCP / skills manager"
  homepage "https://github.com/monkey1wizard/ccync"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/monkey1wizard/ccync/releases/download/v0.1.4/ccync-v0.1.4-darwin-arm64.tar.gz"
      sha256 "ab983e3f46bc19ab15bad6cef764dbd3d5cb6e3ed36b7eeff85fc2e24f53f3df"
    else
      url "https://github.com/monkey1wizard/ccync/releases/download/v0.1.4/ccync-v0.1.4-darwin-x64.tar.gz"
      sha256 "9fe6fa1bc746780bff30b2ddbe2b0ff12e643496813a413b985b14b94842d06f"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/monkey1wizard/ccync/releases/download/v0.1.4/ccync-v0.1.4-linux-arm64.tar.gz"
      sha256 "bd93190af689105eb009e88f140619225ce4c233ff4ffff4fe7271ad8b53a953"
    else
      url "https://github.com/monkey1wizard/ccync/releases/download/v0.1.4/ccync-v0.1.4-linux-x64.tar.gz"
      sha256 "b5002f01e392a5b4587a36647924d8fcbe69d0ae8b089b20f6401ad3841c0734"
    end
  end

  def install
    # ccync is a single self-contained binary (binary-only archive; no packaged
    # source tree). The archive contains a plain `ccync` binary alongside LICENSE.
    bin.install "ccync"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ccync --version")
  end
end
