# Homebrew formula template for ccync — cross-agent plugin / MCP / skills manager
# Placeholders (fill in from checksums.txt after publishing the GitHub Release):
#   v0.1.0             — exact GitHub Release tag (e.g. v0.1.0); used in URLs
#   0.1.0     — version without leading v (e.g. 0.1.0); used in `version`
#   a191e96cb69fe6fc87b5f7af50a81ffe45a2737713a937254ccd7362eb2ca38d   — SHA-256 of ccync-v0.1.0-darwin-x64.tar.gz
#   a8c9f6e1ddc48f47344bcf1d4aa6cf65eefc8fe95908d5ac8fd059ab847688a6 — SHA-256 of ccync-v0.1.0-darwin-arm64.tar.gz
#   e90ab27bc43283f65d2c8c83bd75740cd95cf462685b54af7d708f94640efd1c    — SHA-256 of ccync-v0.1.0-linux-x64.tar.gz
#   62543b2bd28f66b5485e3ce57f5ee01bd0da38d13a16cc25244d081cd2037bb9  — SHA-256 of ccync-v0.1.0-linux-arm64.tar.gz
#
# Generated by: packaging/gen-release-artifacts.sh
# Submit to: https://github.com/monkey1wizard/homebrew-tap (Formula/ccync.rb)
class Ccync < Formula
  desc "Cross-agent plugin / MCP / skills manager"
  homepage "https://github.com/monkey1wizard/ccync"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/monkey1wizard/ccync/releases/download/v0.1.0/ccync-v0.1.0-darwin-arm64.tar.gz"
      sha256 "a8c9f6e1ddc48f47344bcf1d4aa6cf65eefc8fe95908d5ac8fd059ab847688a6"
    else
      url "https://github.com/monkey1wizard/ccync/releases/download/v0.1.0/ccync-v0.1.0-darwin-x64.tar.gz"
      sha256 "a191e96cb69fe6fc87b5f7af50a81ffe45a2737713a937254ccd7362eb2ca38d"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/monkey1wizard/ccync/releases/download/v0.1.0/ccync-v0.1.0-linux-arm64.tar.gz"
      sha256 "62543b2bd28f66b5485e3ce57f5ee01bd0da38d13a16cc25244d081cd2037bb9"
    else
      url "https://github.com/monkey1wizard/ccync/releases/download/v0.1.0/ccync-v0.1.0-linux-x64.tar.gz"
      sha256 "e90ab27bc43283f65d2c8c83bd75740cd95cf462685b54af7d708f94640efd1c"
    end
  end

  def install
    # ccync is a single self-contained binary (binary-only archive; no packaged
    # source tree). The archive contains a plain `ccync` binary alongside LICENSE.
    bin.install "ccync"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ccync --version")
  end
end
