# Homebrew formula template for ccync — cross-agent plugin / MCP / skills manager
# Placeholders (fill in from checksums.txt after publishing the GitHub Release):
#   v0.1.3             — exact GitHub Release tag (e.g. v0.1.0); used in URLs
#   0.1.3     — version without leading v (e.g. 0.1.0); used in `version`
#   9902abb68c8edc1321f57f3395f8e56c62a6c5be1c2840bc1813bd679c737a81   — SHA-256 of ccync-v0.1.3-darwin-x64.tar.gz
#   f091227bbed098e3f5e295a818ef8a70c420e964fbb781802272686825571589 — SHA-256 of ccync-v0.1.3-darwin-arm64.tar.gz
#   59cf80c3ae802bc3723b9cc25a879d20c0736f1a8736617e0fe6b87594157043    — SHA-256 of ccync-v0.1.3-linux-x64.tar.gz
#   8b66e611d45629bf15e1a656b1bc03ff14d05ab81eb82c7c18e1ce1862dd4f8e  — SHA-256 of ccync-v0.1.3-linux-arm64.tar.gz
#
# Generated by: packaging/gen-release-artifacts.sh
# Submit to: https://github.com/monkey1wizard/homebrew-tap (Formula/ccync.rb)
class Ccync < Formula
  desc "Cross-agent plugin / MCP / skills manager"
  homepage "https://github.com/monkey1wizard/ccync"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/monkey1wizard/ccync/releases/download/v0.1.3/ccync-v0.1.3-darwin-arm64.tar.gz"
      sha256 "f091227bbed098e3f5e295a818ef8a70c420e964fbb781802272686825571589"
    else
      url "https://github.com/monkey1wizard/ccync/releases/download/v0.1.3/ccync-v0.1.3-darwin-x64.tar.gz"
      sha256 "9902abb68c8edc1321f57f3395f8e56c62a6c5be1c2840bc1813bd679c737a81"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/monkey1wizard/ccync/releases/download/v0.1.3/ccync-v0.1.3-linux-arm64.tar.gz"
      sha256 "8b66e611d45629bf15e1a656b1bc03ff14d05ab81eb82c7c18e1ce1862dd4f8e"
    else
      url "https://github.com/monkey1wizard/ccync/releases/download/v0.1.3/ccync-v0.1.3-linux-x64.tar.gz"
      sha256 "59cf80c3ae802bc3723b9cc25a879d20c0736f1a8736617e0fe6b87594157043"
    end
  end

  def install
    # ccync is a single self-contained binary (binary-only archive; no packaged
    # source tree). The archive contains a plain `ccync` binary alongside LICENSE.
    bin.install "ccync"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ccync --version")
  end
end
