# Homebrew formula for GAL — Golem Agents Legion bootstrap CLI
# Generated by: gal release --homebrew
# Submit to: https://github.com/monkey1wizard/homebrew-tap
class Gal < Formula
  desc "Document-driven AI working system for cross-tool developer workflows"
  homepage "https://github.com/monkey1wizard/golem-agents-legion"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/monkey1wizard/golem-agents-legion/releases/download/v0.2.3/gal-v0.2.3-darwin-arm64.tar.gz"
      sha256 "e97ff16c3e6303eb64d575b2b9fa73f560dc4e85c5b7a058d34bb02f94ba5951"
    else
      url "https://github.com/monkey1wizard/golem-agents-legion/releases/download/v0.2.3/gal-v0.2.3-darwin-x64.tar.gz"
      sha256 "b4078474f33ffa0e10653b965ad74469ab693a3d5d2de34bbd155c3413e6b63e"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/monkey1wizard/golem-agents-legion/releases/download/v0.2.3/gal-v0.2.3-linux-arm64.tar.gz"
      sha256 "ad9e00043f29a866d2392c56a40ce94dada5459df723e2b91d90cb35d17ff5a1"
    else
      url "https://github.com/monkey1wizard/golem-agents-legion/releases/download/v0.2.3/gal-v0.2.3-linux-x64.tar.gz"
      sha256 "6d982050e66ab03caf38b605f9540d7a06238960f5cfdb531c2409624507a214"
    end
  end

  def install
    # Flat archive: bare `gal` binary + the whole gal-core source payload
    # side by side. Install the binary, then the rest of the tree into
    # pkgshare (share/gal) so `gal refresh` resolves an FHS source root.
    bin.install "gal"
    pkgshare.install Dir["*"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gal --version")
    assert_predicate pkgshare/"skills", :directory?
    assert_predicate pkgshare/"agents", :directory?
  end
end
