# Homebrew formula for GAL — Golem Agents Legion bootstrap CLI
# Generated by: gal release --homebrew
# Submit to: https://github.com/monkey1wizard/homebrew-tap
class Gal < Formula
  desc "Document-driven AI working system for cross-tool developer workflows"
  homepage "https://github.com/monkey1wizard/golem-agents-legion"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/monkey1wizard/golem-agents-legion/releases/download/v0.3.0/gal-v0.3.0-darwin-arm64.tar.gz"
      sha256 "9fde72f6db33a111e3c2ac5a91cf724f32c0fb3015fe3127d04d62baabbc668d"
    else
      url "https://github.com/monkey1wizard/golem-agents-legion/releases/download/v0.3.0/gal-v0.3.0-darwin-x64.tar.gz"
      sha256 "309ddab1a3cd031306ec93cb2d0b270a098090a6b67ac16dc758965758ae382f"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/monkey1wizard/golem-agents-legion/releases/download/v0.3.0/gal-v0.3.0-linux-arm64.tar.gz"
      sha256 "f3c3db909bb09091aad2bf2781f2179a556aaa6b508057e17d30fe46046f476a"
    else
      url "https://github.com/monkey1wizard/golem-agents-legion/releases/download/v0.3.0/gal-v0.3.0-linux-x64.tar.gz"
      sha256 "19aec72fc99d42fd0c2fac9b99ef19650a67e00004cd1047b91676f3559958f9"
    end
  end

  def install
    # Flat archive: bare `gal` binary + the whole gal-core source payload
    # side by side. Install the binary, then the rest of the tree into
    # pkgshare (share/gal) so `gal refresh` resolves an FHS source root.
    bin.install "gal"
    pkgshare.install Dir["*"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gal --version")
    assert_predicate pkgshare/"skills", :directory?
    assert_predicate pkgshare/"agents", :directory?
  end
end
