# Homebrew formula for GAL — Golem Agents Legion bootstrap CLI
# Generated by: gal release --homebrew
# Submit to: https://github.com/monkey1wizard/homebrew-tap
class Gal < Formula
  desc "Document-driven AI working system for cross-tool developer workflows"
  homepage "https://github.com/monkey1wizard/golem-agents-legion"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/monkey1wizard/golem-agents-legion/releases/download/v0.2.1/gal-v0.2.1-darwin-arm64.tar.gz"
      sha256 "e40a398777ff3ad0240067dc7a4ccbf6294123111cf13ea0087493640a6673be"
    else
      url "https://github.com/monkey1wizard/golem-agents-legion/releases/download/v0.2.1/gal-v0.2.1-darwin-x64.tar.gz"
      sha256 "5beac2bb3f14ae0a9b99db5f5914e11fec112232beded3cdefb1075698b43921"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/monkey1wizard/golem-agents-legion/releases/download/v0.2.1/gal-v0.2.1-linux-arm64.tar.gz"
      sha256 "289283c86294297ad5c0dff495985d9f7b1c4afc74ed305ddc0348bb85631622"
    else
      url "https://github.com/monkey1wizard/golem-agents-legion/releases/download/v0.2.1/gal-v0.2.1-linux-x64.tar.gz"
      sha256 "99286e13f6b7b1a7ad114e42e3d40b9062cbc2f5c3a557df01cfb863dbd3f707"
    end
  end

  def install
    # Flat archive: bare `gal` binary + the whole gal-core source payload
    # side by side. Install the binary, then the rest of the tree into
    # pkgshare (share/gal) so `gal refresh` resolves an FHS source root.
    bin.install "gal"
    pkgshare.install Dir["*"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gal --version")
    assert_predicate pkgshare/"skills", :directory?
    assert_predicate pkgshare/"agents", :directory?
  end
end
