# Homebrew formula for WDA
# Generated by: WDA release pipeline
class Wda < Formula
  desc "Framework-independent web design workflow CLI"
  homepage "https://github.com/monkey1wizard/web-design-anchor"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/monkey1wizard/web-design-anchor/releases/download/v0.1.0/wda-v0.1.0-darwin-arm64.tar.gz"
      sha256 "f09558241610d1487f2736c6336a9e8276f7501a7906ed942d1858ee71513531"
    else
      url "https://github.com/monkey1wizard/web-design-anchor/releases/download/v0.1.0/wda-v0.1.0-darwin-x64.tar.gz"
      sha256 "19778922b78a5868c3c000418b3a1d82dd092d93f1398cfc0e9a144efd74dc3c"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/monkey1wizard/web-design-anchor/releases/download/v0.1.0/wda-v0.1.0-linux-arm64.tar.gz"
      sha256 "b80a9cea3200a908c80ab245d63cd67da6b20525648f739b11c44c46515c7153"
    else
      url "https://github.com/monkey1wizard/web-design-anchor/releases/download/v0.1.0/wda-v0.1.0-linux-x64.tar.gz"
      sha256 "dad4134d8aad8dd2b94d7d49066e061fb351cdb90d1dd3f4a289d087d55a3871"
    end
  end

  def install
    bin.install "wda"
    pkgshare.install Dir["*"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wda --version")
    assert_predicate pkgshare/"skills", :directory?
  end
end
